global:
  scrape_interval: 15s
  scrape_timeout: 10s

rule_files:
  - alert.yml
scrape_configs:
  - job_name: apiservices
    metrics_path: /metrics
    static_configs:
      - targets:
        - 'prometheus: 9090'
        - 'bookapi1: 3054'
        - 'badapi1234'

metrics:
  global:
    scrape_interval: 60s
  configs:
  - name: hosted-prometheus
    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['localhost:9100']